name: Build Target
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    env:
      CACHE_KEY: ${{ date "+%Y-%m-%d-%H:%M" }}
    steps:
    - name: Clone
      run: |
        git clone --single-branch --branch master https://github.com/googleapis/googleapis.git
        
    - name: Cache
      uses: actions/cache@v1
      with:
        path: "~/bazel-cache"
        key: ${CACHE_KEY}

    - name: Install Bazel
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        cd googleapis
        "${GITHUB_WORKSPACE}/bin/bazel" test --disk-cache ~/bazel-cache //google/maps/roads/...

    - name: Build
      run: |
        cd googleapis
        "${GITHUB_WORKSPACE}/bin/bazel" build --disk-cache ~/bazel-cache //google/maps/roads/...
