name: Mirror Repo
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/2 * * * *'
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror https://github.com/googleapis/googleapis.git
        cd googleapis.git
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/jpoehnelt/googleapis.git"
        git push --mirror github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
