name: Mirror googleapis/googleapis to jpoehnelt/googleapis
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Clone
      run: git clone --single-branch --branch master https://github.com/googleapis/googleapis.git
    - name: Push
      run: |
        cd googleapis
        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/jpoehnelt/googleapis.git" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_REPO }}
