name: Mirror Repo
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/2 * * * *'
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --single-branch --branch master https://github.com/googleapis/googleapis.git
        cd googleapis
        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/jpoehnelt/googleapis.git" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_REPO }}
